spring:
  application:
    name: kd-ecommerce
  h2:
    console:
      enabled: true
      path: /h2-console # Console will be available at http://localhost:8080/h2-console
  datasource:
    #url: jdbc:h2:mem:testdb # In-memory h2 database named 'testdb'
    url: jdbc:postgresql://localhost:5432/kd-ecommerce-db?currentSchema=public
    username: postgres
    password : Kalidas@123
    #driver-class-name: org.h2.Driver
    driver-class-name: org.postgresql.Driver
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    #defer-datasource-initialization: true
   # database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Automatically creates/updates table schema based on entities
      show-sql: true # Log SQL queries to the console
  app:
    jwtSecret : mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
    jwtExpirationMs : 300000000000
    jwt:
      cookieName: kdEcomJwtCookie
project:
  image: uploads/

logging:
  level:
    # This shows the "CREATE TABLE" attempts
    org.hibernate.tool.schema: DEBUG
    # This shows the SQL being sent to Postgres
    org.hibernate.SQL: DEBUG
    # This shows why connections might be failing
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: DEBUG