spring:
  application:
    name: configdemo
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: prod

build:
  id: 1
  version: 1.02
  name: Default-Build-local-without-Git

management:
  endpoints:
    web:
      exposure:
        include: refresh,health
#  endpoint:
#    refresh:
#      enabled: true
#  endpoint:
#    refresh:
#      enabled: true

