spring:
  application:
    name: config-server-demo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kalidas-khupte-fullStackDev/central-config-server-ymls

server:
  port: 8888